### ISSUE TITLE
Error while running python tool.py run

### ISSUE THREAD

**Issue by Manas-Embold** [tmattellis/DROPvuln#1]
Hi I am getting following error when running subjected line
`py2neo.error.BadInputException: javax.script.ScriptException: groovy.lang.MissingPropertyException: No such property: ANY_SOURCE for class: Script8`

Detailed Error:
root@d3ba42d78094:~/DROPvuln# python tool.py run
Using additional JVM arguments:  -server -XX:+DisableExplicitGC -Dorg.neo4j.server.properties=conf/neo4j-server.properties -Djava.util.logging.config.file=conf/logging.properties -Dlog4j.configuration=file:conf/log4j.properties -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:-OmitStackTraceInFastThrow
Starting Neo4j Server...process [7948]... waiting for server to be ready... OK.
http://localhost:7474/ is ready.
Traceback (most recent call last):
  File "dropVuln.py", line 135, in <module>
    main()
  File "dropVuln.py", line 127, in main
    runQuery(queries[i], queryNames[i],j)
  File "dropVuln.py", line 7, in runQuery
    results = j.runGremlinQuery(query)
  File "/usr/local/lib/python2.7/dist-packages/joern-0.1-py2.7.egg/joern/all.py", line 44, in runGremlinQuery
    return self.gremlin.execute(finalQuery)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/ext/gremlin/__init__.py", line 36, in execute
    response = self.resources["execute_script"].post({"script": script})
  File "/usr/local/lib/python2.7/dist-packages/py2neo/core.py", line 288, in post
    raise_from(self.error_class(message, **content), error)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/util.py", line 215, in raise_from
    raise exception
py2neo.error.BadInputException: javax.script.ScriptException: groovy.lang.MissingPropertyException: No such property: ANY_SOURCE for class: Script8
Stopping Neo4j Server [7948].... done

**Comment by Manas-Embold** [comment]
The issue is with last query.

**Comment by Manas-Embold** [comment]
Better to do exception handling on following line in dropVuln.py, last query gives subjected error on this line
results = j.runGremlinQuery(query)
